version: '3.4'

services:
  #colorstatistic_subscriber:     
  #  build: 
  #    context: .
  #    dockerfile: src/ColorStatistic.Subscriber/Dockerfile
  #  restart: always
  #  depends_on:
  #  - rabbitmq 
  #  networks: 
  #    default:
  #      ipv4_address: 172.10.0.5 

  #colorqueue_subsciber:    
  #  build: 
  #    context: .
  #    dockerfile: src/ColorQueue.Subscriber/Dockerfile
  #  restart: always
  #  depends_on:
  #  - "rabbitmq"
  #  networks: 
  #    default:
  #      ipv4_address: 172.10.0.4 

  colorqueue_producer:
    build:
      context: .
      dockerfile: src/ColorQueue.Producer/Dockerfile
    restart: always
    depends_on:
    - "rabbitmq"     
    networks: 
      default:
        ipv4_address: 172.10.0.3   

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks: 
      default:
        ipv4_address: 172.10.0.2  
        aliases:
          - rabbitmq

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
    